### ISSUE TITLE
Continue development in fork?

### ISSUE THREAD

**Issue by parvit** [parvit/age#1]
Hi @TropicalPenguin, would you be interested in continuing development on my fork?

Or maybe you could create a fork in your account and i would develop the features you want on that.

Let me know.

**Comment by TropicalPenguin** [comment]
Hi @parvit; I'd be interested to try, certainly. Even if it doesn't turn into something the original project wants to merge, it might give me something to build on while they craft an alternate implementation. While I can acknowledge that mutating ops are going to be inherently more complex than read ops, I'm not sure I find it plausible that the difference between the setting of one property vs the setting of multiple properties - in the context of a single op, at least - is really going to introduce particularly more complexity. It didn't for RedisGraph, though it's of course possible there's something unique about the AGE arch that I'm missing.

Given your earlier questions, I feel the need to disclose on the chance it's not now obvious: I'm not an AGE developer, so I probably won't be able to answer questions about the code/architecture (the code highlight from the earlier thread was just from a brief search). And given others' apparent reticence about helping someone with a financial stake, you might be somewhat on your own in solving any problems.

And perhaps it would be prudent for me to consider the possibility (it might be remote, but it's difficult to say) that someone else provides a working solution before you do (it's still not clear just _how_ actively this issue is being worked on by others). I think it would be in bad faith on my part if I rewarded the bounty to someone who only provided a solution later. Hopefully you find it an interesting problem anyway regardless of the bounty, but, I just want to be up-front about a potential frustration.

**Comment by parvit** [comment]
I understand, i'll recreate the ticket in here so we can interact without the interference of others.

Of course i acknowledge that if the original ticket is solved before than its a fair result for them.

If on the other hand i manage to find a solution we can consider to push it upstream, how does that sound?

**Comment by TropicalPenguin** [comment]
I would temporarily close the original ticket for the purpose of releasing the bounty anyway, so not sure a recreated ticket is necessary.

> If on the other hand i manage to find a solution we can consider to push it upstream, how does that sound?

Yeah, might as well try; the original project can then take it or leave it.
